-- FAKE_APPLY: This file content is commented out to sync migration history.
-- CREATE TABLE IF NOT EXISTS "Task" (
-- 	"id" varchar(191) PRIMARY KEY NOT NULL,
-- 	"task_type" "task_type" NOT NULL,
-- 	"status" "task_status" DEFAULT 'pending' NOT NULL,
-- 	"document_id" varchar(191),
-- 	"from_page" integer,
-- 	"to_page" integer,
-- 	"priority" integer DEFAULT 0 NOT NULL,
-- 	"progress" integer DEFAULT 0 NOT NULL,
-- 	"progress_msg" text,
-- 	"begin_at" timestamp with time zone,
-- 	"completed_at" timestamp with time zone,
-- 	"process_duration" integer DEFAULT 0,
-- 	"retry_count" integer DEFAULT 0 NOT NULL,
-- 	"max_retries" integer DEFAULT 3 NOT NULL,
-- 	"digest" varchar(255),
-- 	"chunk_ids" text,
-- 	"error" text,
-- 	"error_stack" text,
-- 	"config" jsonb DEFAULT '{}'::jsonb,
-- 	"result" jsonb DEFAULT '{}'::jsonb,
-- 	"creator_id" uuid,
-- 	"metadata" jsonb DEFAULT '{}'::jsonb,
-- 	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
-- 	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
-- );
-- --> statement-breakpoint
-- DO $$ BEGIN
--  ALTER TABLE "Task" ADD CONSTRAINT "Task_document_id_KnowledgeBaseDocument_id_fk" FOREIGN KEY ("document_id") REFERENCES "public"."KnowledgeBaseDocument"("id") ON DELETE cascade ON UPDATE no action;
-- EXCEPTION
--  WHEN duplicate_object THEN null;
-- END $$;
-- --> statement-breakpoint
-- DO $$ BEGIN
--  ALTER TABLE "Task" ADD CONSTRAINT "Task_creator_id_User_id_fk" FOREIGN KEY ("creator_id") REFERENCES "public"."User"("id") ON DELETE set null ON UPDATE no action;
-- EXCEPTION
--  WHEN duplicate_object THEN null;
-- END $$;
-- --> statement-breakpoint
-- CREATE INDEX IF NOT EXISTS "task_status_idx" ON "Task" USING btree ("status");--> statement-breakpoint
-- CREATE INDEX IF NOT EXISTS "task_type_idx" ON "Task" USING btree ("task_type");--> statement-breakpoint
-- CREATE INDEX IF NOT EXISTS "task_document_idx" ON "Task" USING btree ("document_id");--> statement-breakpoint
-- CREATE INDEX IF NOT EXISTS "task_priority_idx" ON "Task" USING btree ("priority");--> statement-breakpoint
-- CREATE INDEX IF NOT EXISTS "task_digest_idx" ON "Task" USING btree ("digest");--> statement-breakpoint
-- CREATE INDEX IF NOT EXISTS "task_created_at_idx" ON "Task" USING btree ("created_at");