-- FAKE_APPLY: This file content is commented out to sync migration history.
-- DO $$ BEGIN
--  CREATE TYPE "public"."parser_type" AS ENUM('naive', 'qa', 'book', 'presentation', 'manual', 'table');
-- EXCEPTION
--  WHEN duplicate_object THEN null;
-- END $$;
-- --> statement-breakpoint
-- ALTER TABLE "KnowledgeBaseDocument" ADD COLUMN "parser_id" "parser_type" DEFAULT 'naive' NOT NULL;--> statement-breakpoint
-- ALTER TABLE "KnowledgeBaseDocument" ADD COLUMN "process_begin_at" timestamp with time zone;--> statement-breakpoint
-- ALTER TABLE "KnowledgeBaseDocument" ADD COLUMN "process_duration" integer DEFAULT 0;